#############################################################################
# Makefile for building: difa.app/Contents/MacOS/difa
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  difa.pro
# Template: app
# Command: /usr/local/bin/qmake -o Makefile difa.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/Cellar/cln/1.3.4/include -I/usr/local/Cellar/qt5/5.7.0/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt5/5.7.0/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt5/5.7.0/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/usr/local/Cellar/qt5/5.7.0/mkspecs/macx-clang -F/usr/local/Cellar/qt5/5.7.0/lib
QMAKE         = /usr/local/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = difa1.0.0
DISTDIR = /Users/tatiana/Diffurs/.tmp/difa1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8
LIBS          = $(SUBLIBS) -F/usr/local/Cellar/qt5/5.7.0/lib -L/usr/local/Cellar/cln/1.3.4/lib -lcln -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		symb/src/array.cpp \
		symb/src/cloning.cpp \
		symb/src/constants.cpp \
		symb/src/derive.cpp \
		symb/src/equation.cpp \
		symb/src/functions.cpp \
		symb/src/identity.cpp \
		symb/src/integrate.cpp \
		symb/src/matnorm.cpp \
		symb/src/matrix.cpp \
		symb/src/multinomial.cpp \
		symb/src/number.cpp \
		symb/src/polynomial.cpp \
		symb/src/product.cpp \
		symb/src/quatern.cpp \
		symb/src/rational.cpp \
		symb/src/solve.cpp \
		symb/src/sum.cpp \
		symb/src/symbol.cpp \
		symb/src/symbolic.cpp \
		symb/src/symbolicc++.cpp \
		symb/src/symerror.cpp \
		symb/src/symmatrix.cpp \
		symb/src/vecnorm.cpp \
		symb/src/vector.cpp \
		symb/src/verylong.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		array.o \
		cloning.o \
		constants.o \
		derive.o \
		equation.o \
		functions.o \
		identity.o \
		integrate.o \
		matnorm.o \
		matrix.o \
		multinomial.o \
		number.o \
		polynomial.o \
		product.o \
		quatern.o \
		rational.o \
		solve.o \
		sum.o \
		symbol.o \
		symbolic.o \
		symbolicc++.o \
		symerror.o \
		symmatrix.o \
		vecnorm.o \
		vector.o \
		verylong.o \
		moc_mainwindow.o
DIST          = /usr/local/Cellar/qt5/5.7.0/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/qdevice.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/link_pkgconfig.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/file_copies.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/lex.prf \
		difa.pro mainwindow.h \
		symb/include/array.h \
		symb/include/cloning.h \
		symb/include/derive.h \
		symb/include/identity.h \
		symb/include/matnorm.h \
		symb/include/matrix.h \
		symb/include/multinomial.h \
		symb/include/polynomial.h \
		symb/include/quatern.h \
		symb/include/rational.h \
		symb/include/symbolicc++.h \
		symb/include/vecnorm.h \
		symb/include/vector.h \
		symb/include/verylong.h \
		symb/include/symbolic/constants.h \
		symb/include/symbolic/equation.h \
		symb/include/symbolic/functions.h \
		symb/include/symbolic/integrate.h \
		symb/include/symbolic/number.h \
		symb/include/symbolic/product.h \
		symb/include/symbolic/solve.h \
		symb/include/symbolic/sum.h \
		symb/include/symbolic/symbol.h \
		symb/include/symbolic/symbolic.h \
		symb/include/symbolic/symbolicc++.h \
		symb/include/symbolic/symerror.h \
		symb/include/symbolic/symmatrix.h main.cpp \
		mainwindow.cpp \
		symb/src/array.cpp \
		symb/src/cloning.cpp \
		symb/src/constants.cpp \
		symb/src/derive.cpp \
		symb/src/equation.cpp \
		symb/src/functions.cpp \
		symb/src/identity.cpp \
		symb/src/integrate.cpp \
		symb/src/matnorm.cpp \
		symb/src/matrix.cpp \
		symb/src/multinomial.cpp \
		symb/src/number.cpp \
		symb/src/polynomial.cpp \
		symb/src/product.cpp \
		symb/src/quatern.cpp \
		symb/src/rational.cpp \
		symb/src/solve.cpp \
		symb/src/sum.cpp \
		symb/src/symbol.cpp \
		symb/src/symbolic.cpp \
		symb/src/symbolicc++.cpp \
		symb/src/symerror.cpp \
		symb/src/symmatrix.cpp \
		symb/src/vecnorm.cpp \
		symb/src/vector.cpp \
		symb/src/verylong.cpp
QMAKE_TARGET  = difa
DESTDIR       = 
TARGET        = difa.app/Contents/MacOS/difa


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@test -d difa.app/Contents/MacOS/ || mkdir -p difa.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: difa.pro /usr/local/Cellar/qt5/5.7.0/mkspecs/macx-clang/qmake.conf /usr/local/Cellar/qt5/5.7.0/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/qdevice.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/link_pkgconfig.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/file_copies.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt5/5.7.0/mkspecs/features/lex.prf \
		difa.pro \
		/usr/local/Cellar/qt5/5.7.0/lib/QtWidgets.framework/QtWidgets.prl \
		/usr/local/Cellar/qt5/5.7.0/lib/QtGui.framework/QtGui.prl \
		/usr/local/Cellar/qt5/5.7.0/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile difa.pro
/usr/local/Cellar/qt5/5.7.0/mkspecs/features/spec_pre.prf:
/usr/local/Cellar/qt5/5.7.0/mkspecs/qdevice.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/features/device_config.prf:
/usr/local/Cellar/qt5/5.7.0/mkspecs/common/unix.conf:
/usr/local/Cellar/qt5/5.7.0/mkspecs/common/mac.conf:
/usr/local/Cellar/qt5/5.7.0/mkspecs/common/macx.conf:
/usr/local/Cellar/qt5/5.7.0/mkspecs/common/sanitize.conf:
/usr/local/Cellar/qt5/5.7.0/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt5/5.7.0/mkspecs/common/gcc-base-mac.conf:
/usr/local/Cellar/qt5/5.7.0/mkspecs/common/clang.conf:
/usr/local/Cellar/qt5/5.7.0/mkspecs/common/clang-mac.conf:
/usr/local/Cellar/qt5/5.7.0/mkspecs/qconfig.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dcore.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dextras.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dinput.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dquick.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3drender.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_charts.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_charts_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_clucene_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_core.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_datavisualization.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_datavisualization_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_designer.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_gamepad.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_gamepad_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_gui.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_help.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_location.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_location_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_macextras.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_macextras_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_network.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_purchasing.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_purchasing_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_qml.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_quick.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_script.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_scxml.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_serialbus.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_sql.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_svg.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_webchannel.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_webengine.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_webview.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_webview_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_xml.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/Cellar/qt5/5.7.0/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt5/5.7.0/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt5/5.7.0/mkspecs/macx-clang/qmake.conf:
/usr/local/Cellar/qt5/5.7.0/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/local/Cellar/qt5/5.7.0/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt5/5.7.0/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt5/5.7.0/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt5/5.7.0/mkspecs/features/resolve_config.prf:
/usr/local/Cellar/qt5/5.7.0/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt5/5.7.0/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt5/5.7.0/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt5/5.7.0/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt5/5.7.0/mkspecs/features/link_pkgconfig.prf:
/usr/local/Cellar/qt5/5.7.0/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt5/5.7.0/mkspecs/features/qt.prf:
/usr/local/Cellar/qt5/5.7.0/mkspecs/features/resources.prf:
/usr/local/Cellar/qt5/5.7.0/mkspecs/features/moc.prf:
/usr/local/Cellar/qt5/5.7.0/mkspecs/features/unix/opengl.prf:
/usr/local/Cellar/qt5/5.7.0/mkspecs/features/uic.prf:
/usr/local/Cellar/qt5/5.7.0/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt5/5.7.0/mkspecs/features/file_copies.prf:
/usr/local/Cellar/qt5/5.7.0/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt5/5.7.0/mkspecs/features/testcase_targets.prf:
/usr/local/Cellar/qt5/5.7.0/mkspecs/features/exceptions.prf:
/usr/local/Cellar/qt5/5.7.0/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt5/5.7.0/mkspecs/features/lex.prf:
difa.pro:
/usr/local/Cellar/qt5/5.7.0/lib/QtWidgets.framework/QtWidgets.prl:
/usr/local/Cellar/qt5/5.7.0/lib/QtGui.framework/QtGui.prl:
/usr/local/Cellar/qt5/5.7.0/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile difa.pro

qmake_all: FORCE

difa.app/Contents/PkgInfo: 
	@test -d difa.app/Contents || mkdir -p difa.app/Contents
	@$(DEL_FILE) difa.app/Contents/PkgInfo
	@echo "APPL????" > difa.app/Contents/PkgInfo
difa.app/Contents/Resources/empty.lproj: 
	@test -d difa.app/Contents/Resources || mkdir -p difa.app/Contents/Resources
	@touch difa.app/Contents/Resources/empty.lproj
	
difa.app/Contents/Info.plist: 
	@test -d difa.app/Contents || mkdir -p difa.app/Contents
	@$(DEL_FILE) difa.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,Kutuzova.difa,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,difa,g" -e "s,@LIBRARY@,difa,g" -e "s,@TYPEINFO@,????,g" /usr/local/Cellar/qt5/5.7.0/mkspecs/macx-clang/Info.plist.app >difa.app/Contents/Info.plist

all: Makefile \
		difa.app/Contents/PkgInfo \
		difa.app/Contents/Resources/empty.lproj \
		difa.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h symb/include/array.h symb/include/cloning.h symb/include/derive.h symb/include/identity.h symb/include/matnorm.h symb/include/matrix.h symb/include/multinomial.h symb/include/polynomial.h symb/include/quatern.h symb/include/rational.h symb/include/symbolicc++.h symb/include/vecnorm.h symb/include/vector.h symb/include/verylong.h symb/include/symbolic/constants.h symb/include/symbolic/equation.h symb/include/symbolic/functions.h symb/include/symbolic/integrate.h symb/include/symbolic/number.h symb/include/symbolic/product.h symb/include/symbolic/solve.h symb/include/symbolic/sum.h symb/include/symbolic/symbol.h symb/include/symbolic/symbolic.h symb/include/symbolic/symbolicc++.h symb/include/symbolic/symerror.h symb/include/symbolic/symmatrix.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp symb/src/array.cpp symb/src/cloning.cpp symb/src/constants.cpp symb/src/derive.cpp symb/src/equation.cpp symb/src/functions.cpp symb/src/identity.cpp symb/src/integrate.cpp symb/src/matnorm.cpp symb/src/matrix.cpp symb/src/multinomial.cpp symb/src/number.cpp symb/src/polynomial.cpp symb/src/product.cpp symb/src/quatern.cpp symb/src/rational.cpp symb/src/solve.cpp symb/src/sum.cpp symb/src/symbol.cpp symb/src/symbolic.cpp symb/src/symbolicc++.cpp symb/src/symerror.cpp symb/src/symmatrix.cpp symb/src/vecnorm.cpp symb/src/vector.cpp symb/src/verylong.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r difa.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: /usr/local/Cellar/qt5/5.7.0/lib/QtWidgets.framework/Headers/QMainWindow \
		/usr/local/Cellar/qt5/5.7.0/lib/QtWidgets.framework/Headers/qmainwindow.h \
		mainwindow.h \
		/usr/local/Cellar/qt5/5.7.0/bin/moc
	/usr/local/Cellar/qt5/5.7.0/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/usr/local/Cellar/qt5/5.7.0/mkspecs/macx-clang -I/Users/tatiana/Diffurs -I/usr/local/Cellar/cln/1.3.4/include -I/usr/local/Cellar/qt5/5.7.0/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt5/5.7.0/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt5/5.7.0/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/usr/local/Cellar/qt5/5.7.0/lib mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		/usr/local/Cellar/qt5/5.7.0/bin/uic
	/usr/local/Cellar/qt5/5.7.0/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		/usr/local/Cellar/qt5/5.7.0/lib/QtWidgets.framework/Headers/QMainWindow \
		/usr/local/Cellar/qt5/5.7.0/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/usr/local/Cellar/qt5/5.7.0/lib/QtWidgets.framework/Headers/QApplication \
		/usr/local/Cellar/qt5/5.7.0/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/usr/local/Cellar/qt5/5.7.0/lib/QtWidgets.framework/Headers/QMainWindow \
		/usr/local/Cellar/qt5/5.7.0/lib/QtWidgets.framework/Headers/qmainwindow.h \
		ui_mainwindow.h \
		symb/include/symbolicc++.h \
		symb/include/symbolic/symbolicc++.h \
		symb/include/cloning.h \
		symb/include/identity.h \
		symb/include/symbolic/symbolic.h \
		symb/include/symbolic/equation.h \
		symb/include/symbolic/number.h \
		symb/include/rational.h \
		symb/include/verylong.h \
		symb/include/symbolic/product.h \
		symb/include/symbolic/sum.h \
		symb/include/symbolic/symbol.h \
		symb/include/symbolic/functions.h \
		symb/include/symbolic/symmatrix.h \
		symb/include/matrix.h \
		symb/include/vector.h \
		symb/include/symbolic/symerror.h \
		symb/include/symbolic/constants.h \
		symb/include/symbolic/integrate.h \
		symb/include/symbolic/solve.h \
		/usr/local/Cellar/qt5/5.7.0/lib/QtCore.framework/Headers/QDebug \
		/usr/local/Cellar/qt5/5.7.0/lib/QtCore.framework/Headers/qdebug.h \
		/usr/local/Cellar/qt5/5.7.0/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt5/5.7.0/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/Cellar/qt5/5.7.0/lib/QtGui.framework/Headers/QPixmap \
		/usr/local/Cellar/qt5/5.7.0/lib/QtGui.framework/Headers/qpixmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

array.o: symb/src/array.cpp symb/include/array.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o array.o symb/src/array.cpp

cloning.o: symb/src/cloning.cpp symb/include/cloning.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cloning.o symb/src/cloning.cpp

constants.o: symb/src/constants.cpp symb/include/symbolic/symbolicc++.h \
		symb/include/cloning.h \
		symb/include/identity.h \
		symb/include/symbolic/symbolic.h \
		symb/include/symbolic/equation.h \
		symb/include/symbolic/number.h \
		symb/include/rational.h \
		symb/include/verylong.h \
		symb/include/symbolic/product.h \
		symb/include/symbolic/sum.h \
		symb/include/symbolic/symbol.h \
		symb/include/symbolic/functions.h \
		symb/include/symbolic/symmatrix.h \
		symb/include/matrix.h \
		symb/include/vector.h \
		symb/include/symbolic/symerror.h \
		symb/include/symbolic/constants.h \
		symb/include/symbolic/integrate.h \
		symb/include/symbolic/solve.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o constants.o symb/src/constants.cpp

derive.o: symb/src/derive.cpp symb/include/derive.h \
		symb/include/identity.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o derive.o symb/src/derive.cpp

equation.o: symb/src/equation.cpp symb/include/symbolic/symbolicc++.h \
		symb/include/cloning.h \
		symb/include/identity.h \
		symb/include/symbolic/symbolic.h \
		symb/include/symbolic/equation.h \
		symb/include/symbolic/number.h \
		symb/include/rational.h \
		symb/include/verylong.h \
		symb/include/symbolic/product.h \
		symb/include/symbolic/sum.h \
		symb/include/symbolic/symbol.h \
		symb/include/symbolic/functions.h \
		symb/include/symbolic/symmatrix.h \
		symb/include/matrix.h \
		symb/include/vector.h \
		symb/include/symbolic/symerror.h \
		symb/include/symbolic/constants.h \
		symb/include/symbolic/integrate.h \
		symb/include/symbolic/solve.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o equation.o symb/src/equation.cpp

functions.o: symb/src/functions.cpp symb/include/symbolic/symbolicc++.h \
		symb/include/cloning.h \
		symb/include/identity.h \
		symb/include/symbolic/symbolic.h \
		symb/include/symbolic/equation.h \
		symb/include/symbolic/number.h \
		symb/include/rational.h \
		symb/include/verylong.h \
		symb/include/symbolic/product.h \
		symb/include/symbolic/sum.h \
		symb/include/symbolic/symbol.h \
		symb/include/symbolic/functions.h \
		symb/include/symbolic/symmatrix.h \
		symb/include/matrix.h \
		symb/include/vector.h \
		symb/include/symbolic/symerror.h \
		symb/include/symbolic/constants.h \
		symb/include/symbolic/integrate.h \
		symb/include/symbolic/solve.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o functions.o symb/src/functions.cpp

identity.o: symb/src/identity.cpp symb/include/identity.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o identity.o symb/src/identity.cpp

integrate.o: symb/src/integrate.cpp symb/include/symbolic/symbolicc++.h \
		symb/include/cloning.h \
		symb/include/identity.h \
		symb/include/symbolic/symbolic.h \
		symb/include/symbolic/equation.h \
		symb/include/symbolic/number.h \
		symb/include/rational.h \
		symb/include/verylong.h \
		symb/include/symbolic/product.h \
		symb/include/symbolic/sum.h \
		symb/include/symbolic/symbol.h \
		symb/include/symbolic/functions.h \
		symb/include/symbolic/symmatrix.h \
		symb/include/matrix.h \
		symb/include/vector.h \
		symb/include/symbolic/symerror.h \
		symb/include/symbolic/constants.h \
		symb/include/symbolic/integrate.h \
		symb/include/symbolic/solve.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o integrate.o symb/src/integrate.cpp

matnorm.o: symb/src/matnorm.cpp symb/include/matnorm.h \
		symb/include/vector.h \
		symb/include/identity.h \
		symb/include/vecnorm.h \
		symb/include/matrix.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o matnorm.o symb/src/matnorm.cpp

matrix.o: symb/src/matrix.cpp symb/include/matrix.h \
		symb/include/identity.h \
		symb/include/vector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o matrix.o symb/src/matrix.cpp

multinomial.o: symb/src/multinomial.cpp symb/include/multinomial.h \
		symb/include/identity.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o multinomial.o symb/src/multinomial.cpp

number.o: symb/src/number.cpp symb/include/symbolic/symbolicc++.h \
		symb/include/cloning.h \
		symb/include/identity.h \
		symb/include/symbolic/symbolic.h \
		symb/include/symbolic/equation.h \
		symb/include/symbolic/number.h \
		symb/include/rational.h \
		symb/include/verylong.h \
		symb/include/symbolic/product.h \
		symb/include/symbolic/sum.h \
		symb/include/symbolic/symbol.h \
		symb/include/symbolic/functions.h \
		symb/include/symbolic/symmatrix.h \
		symb/include/matrix.h \
		symb/include/vector.h \
		symb/include/symbolic/symerror.h \
		symb/include/symbolic/constants.h \
		symb/include/symbolic/integrate.h \
		symb/include/symbolic/solve.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o number.o symb/src/number.cpp

polynomial.o: symb/src/polynomial.cpp symb/include/polynomial.h \
		symb/include/identity.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o polynomial.o symb/src/polynomial.cpp

product.o: symb/src/product.cpp symb/include/symbolic/symbolicc++.h \
		symb/include/cloning.h \
		symb/include/identity.h \
		symb/include/symbolic/symbolic.h \
		symb/include/symbolic/equation.h \
		symb/include/symbolic/number.h \
		symb/include/rational.h \
		symb/include/verylong.h \
		symb/include/symbolic/product.h \
		symb/include/symbolic/sum.h \
		symb/include/symbolic/symbol.h \
		symb/include/symbolic/functions.h \
		symb/include/symbolic/symmatrix.h \
		symb/include/matrix.h \
		symb/include/vector.h \
		symb/include/symbolic/symerror.h \
		symb/include/symbolic/constants.h \
		symb/include/symbolic/integrate.h \
		symb/include/symbolic/solve.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o product.o symb/src/product.cpp

quatern.o: symb/src/quatern.cpp symb/include/quatern.h \
		symb/include/identity.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quatern.o symb/src/quatern.cpp

rational.o: symb/src/rational.cpp symb/include/rational.h \
		symb/include/identity.h \
		symb/include/verylong.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rational.o symb/src/rational.cpp

solve.o: symb/src/solve.cpp symb/include/symbolic/symbolicc++.h \
		symb/include/cloning.h \
		symb/include/identity.h \
		symb/include/symbolic/symbolic.h \
		symb/include/symbolic/equation.h \
		symb/include/symbolic/number.h \
		symb/include/rational.h \
		symb/include/verylong.h \
		symb/include/symbolic/product.h \
		symb/include/symbolic/sum.h \
		symb/include/symbolic/symbol.h \
		symb/include/symbolic/functions.h \
		symb/include/symbolic/symmatrix.h \
		symb/include/matrix.h \
		symb/include/vector.h \
		symb/include/symbolic/symerror.h \
		symb/include/symbolic/constants.h \
		symb/include/symbolic/integrate.h \
		symb/include/symbolic/solve.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o solve.o symb/src/solve.cpp

sum.o: symb/src/sum.cpp symb/include/symbolic/symbolicc++.h \
		symb/include/cloning.h \
		symb/include/identity.h \
		symb/include/symbolic/symbolic.h \
		symb/include/symbolic/equation.h \
		symb/include/symbolic/number.h \
		symb/include/rational.h \
		symb/include/verylong.h \
		symb/include/symbolic/product.h \
		symb/include/symbolic/sum.h \
		symb/include/symbolic/symbol.h \
		symb/include/symbolic/functions.h \
		symb/include/symbolic/symmatrix.h \
		symb/include/matrix.h \
		symb/include/vector.h \
		symb/include/symbolic/symerror.h \
		symb/include/symbolic/constants.h \
		symb/include/symbolic/integrate.h \
		symb/include/symbolic/solve.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sum.o symb/src/sum.cpp

symbol.o: symb/src/symbol.cpp symb/include/symbolic/symbolicc++.h \
		symb/include/cloning.h \
		symb/include/identity.h \
		symb/include/symbolic/symbolic.h \
		symb/include/symbolic/equation.h \
		symb/include/symbolic/number.h \
		symb/include/rational.h \
		symb/include/verylong.h \
		symb/include/symbolic/product.h \
		symb/include/symbolic/sum.h \
		symb/include/symbolic/symbol.h \
		symb/include/symbolic/functions.h \
		symb/include/symbolic/symmatrix.h \
		symb/include/matrix.h \
		symb/include/vector.h \
		symb/include/symbolic/symerror.h \
		symb/include/symbolic/constants.h \
		symb/include/symbolic/integrate.h \
		symb/include/symbolic/solve.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o symbol.o symb/src/symbol.cpp

symbolic.o: symb/src/symbolic.cpp symb/include/symbolic/symbolicc++.h \
		symb/include/cloning.h \
		symb/include/identity.h \
		symb/include/symbolic/symbolic.h \
		symb/include/symbolic/equation.h \
		symb/include/symbolic/number.h \
		symb/include/rational.h \
		symb/include/verylong.h \
		symb/include/symbolic/product.h \
		symb/include/symbolic/sum.h \
		symb/include/symbolic/symbol.h \
		symb/include/symbolic/functions.h \
		symb/include/symbolic/symmatrix.h \
		symb/include/matrix.h \
		symb/include/vector.h \
		symb/include/symbolic/symerror.h \
		symb/include/symbolic/constants.h \
		symb/include/symbolic/integrate.h \
		symb/include/symbolic/solve.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o symbolic.o symb/src/symbolic.cpp

symbolicc++.o: symb/src/symbolicc++.cpp symb/include/symbolic/symbolicc++.h \
		symb/include/cloning.h \
		symb/include/identity.h \
		symb/include/symbolic/symbolic.h \
		symb/include/symbolic/equation.h \
		symb/include/symbolic/number.h \
		symb/include/rational.h \
		symb/include/verylong.h \
		symb/include/symbolic/product.h \
		symb/include/symbolic/sum.h \
		symb/include/symbolic/symbol.h \
		symb/include/symbolic/functions.h \
		symb/include/symbolic/symmatrix.h \
		symb/include/matrix.h \
		symb/include/vector.h \
		symb/include/symbolic/symerror.h \
		symb/include/symbolic/constants.h \
		symb/include/symbolic/integrate.h \
		symb/include/symbolic/solve.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o symbolicc++.o symb/src/symbolicc++.cpp

symerror.o: symb/src/symerror.cpp symb/include/symbolic/symbolicc++.h \
		symb/include/cloning.h \
		symb/include/identity.h \
		symb/include/symbolic/symbolic.h \
		symb/include/symbolic/equation.h \
		symb/include/symbolic/number.h \
		symb/include/rational.h \
		symb/include/verylong.h \
		symb/include/symbolic/product.h \
		symb/include/symbolic/sum.h \
		symb/include/symbolic/symbol.h \
		symb/include/symbolic/functions.h \
		symb/include/symbolic/symmatrix.h \
		symb/include/matrix.h \
		symb/include/vector.h \
		symb/include/symbolic/symerror.h \
		symb/include/symbolic/constants.h \
		symb/include/symbolic/integrate.h \
		symb/include/symbolic/solve.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o symerror.o symb/src/symerror.cpp

symmatrix.o: symb/src/symmatrix.cpp symb/include/symbolic/symbolicc++.h \
		symb/include/cloning.h \
		symb/include/identity.h \
		symb/include/symbolic/symbolic.h \
		symb/include/symbolic/equation.h \
		symb/include/symbolic/number.h \
		symb/include/rational.h \
		symb/include/verylong.h \
		symb/include/symbolic/product.h \
		symb/include/symbolic/sum.h \
		symb/include/symbolic/symbol.h \
		symb/include/symbolic/functions.h \
		symb/include/symbolic/symmatrix.h \
		symb/include/matrix.h \
		symb/include/vector.h \
		symb/include/symbolic/symerror.h \
		symb/include/symbolic/constants.h \
		symb/include/symbolic/integrate.h \
		symb/include/symbolic/solve.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o symmatrix.o symb/src/symmatrix.cpp

vecnorm.o: symb/src/vecnorm.cpp symb/include/vecnorm.h \
		symb/include/vector.h \
		symb/include/identity.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vecnorm.o symb/src/vecnorm.cpp

vector.o: symb/src/vector.cpp symb/include/vector.h \
		symb/include/identity.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vector.o symb/src/vector.cpp

verylong.o: symb/src/verylong.cpp symb/include/verylong.h \
		symb/include/identity.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o verylong.o symb/src/verylong.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

